=== aeon-php/automation/automation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation source="https://aeon-php.org/docs/">
            This Schema file defines the rules by which the XML configuration file of Aeon Automation Configuration may be structured.
        </xs:documentation>
        <xs:appinfo source="https://aeon-php.org/"/>
    </xs:annotation>
    <xs:element name="aeon" type="aeonType">
        <xs:annotation>
            <xs:documentation>Root Element</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="aeonType">
        <xs:annotation>
            <xs:documentation>The main type specifying the document structure</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="projects" type="projectsType" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="projectsType">
        <xs:sequence>
            <xs:element name="project" type="projectType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="projectType">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== aeon-php/automation/automation.xml
<?xml version="1.0" encoding="UTF-8"?>
<aeon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="automation.xsd">
    <projects>
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/calendar" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/business-hours" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/calendar-doctrine" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/calendar-twig" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/calendar-holidays" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/calendar-holidays-yasumi" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/calendar-twig" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/sleep" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/retry" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/rate-limiter" />
        <project path="/Users/norzechowicz/Workspace/PHP/aeon-php/symfony-aeon-bundle" />
    </projects>
</aeon>
